version: "5"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - bootapp
  auth-service:
    build: .
    container_name: auth-service
    ports:
      - "8070:8050"
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/authService
    networks:
      - bootapp

networks:
    bootapp:
        driver: bridge

volumes:
  mongo-data:
    driver: local